USE Empresa

INSERT INTO Produtos
VALUES ('SUCO DE UVA',
(SELECT CODFOR 
FROM Fornecedores 
WHERE EMPRESA = 'REFRESCOS AMERICANAS LTDA'),
(SELECT CODCATEGORIA
FROM CATEGORIAS
WHERE DESCR = 'BEBIDAS'),
4.50, 10, 0)

SELECT * FROM Produtos

INSERT INTO Funcionarios
VALUES  ('DA SILVA','JOÃO', 'GERENTE', NULL, NULL, 'TIANGUÁ', NULL, 'BRASIL', NULL,
(SELECT AVG(SALARIO) MEDIA_SALARIO
FROM Funcionarios
WHERE CARGO LIKE 'GERENTE%'))

SELECT * FROM Funcionarios

→ Criar uma tabela e popular com o nome dos funcionários, o
salário e o nome do departamento associado.

SELECT NOME, SALARIO INTO TBFUNCIONARIOSALARIO
FROM Funcionarios

SELECT * FROM TBFUNCIONARIOSALARIO

CRIAR UMA TABELA COM NOME TEMPORARIA COM A DESCRIÇÃO DO PRODUTO E A EMPRESA DO FORNECEDOR DAQUELE PRODUTO

SELECT DESCR, EMPRESA INTO TEMPORARIA
FROM PRODUTOS AS P JOIN Fornecedores AS F
ON P.CodFor = F.CodFor

SELECT * FROM TEMPORARIA
