use SistemaAcademicoBCC

→ Obter a média de créditos cursada por semestre pelos alunos
do curso de Ciência da Computação.

SELECT SUM (DIS_CARGA_HORARIA)/20, ALU_NOME
FROM tbDisciplina AS D JOIN tbOfertaDisciplina AS OD
ON D.DIS_CODIGO = OD.DIS_CODIGO
JOIN
tbAlunoMatricula AS AM
ON OD.ODI_CODIGO = AM.ODI_CODIGO
JOIN
tbAluno AS A
ON AM.ALU_CODIGO = A.ALU_CODIGO
JOIN
tbCurso AS C
ON A.CUR_CODIGO = C.CUR_CODIGO
WHERE CUR_NOME = 'BACHARELADO EM Ciência da Computação'
GROUP BY ALU_NOME, ODI_SEMESTRE, ODI_ANO

POR MEIO DE UMA VISÃO

CREATE VIEW VW_CREDITOSALUNOS
AS
SELECT SUM (DIS_CARGA_HORARIA)/20 AS SOMA, ALU_NOME
FROM tbDisciplina AS D JOIN tbOfertaDisciplina AS OD
ON D.DIS_CODIGO = OD.DIS_CODIGO
JOIN
tbAlunoMatricula AS AM
ON OD.ODI_CODIGO = AM.ODI_CODIGO
JOIN
tbAluno AS A
ON AM.ALU_CODIGO = A.ALU_CODIGO
JOIN
tbCurso AS C
ON A.CUR_CODIGO = C.CUR_CODIGO
WHERE CUR_NOME = 'BACHARELADO EM Ciência da Computação'
GROUP BY ALU_NOME, ODI_SEMESTRE, ODI_ANO

SELECT AVG(SOMA) AS MEDIADECREDITOS
FROM VW_CREDITOSALUNOS