use sistemaacademicobcc

SELECT 
 (SELECT COUNT(*) QTDE_DISCIPLINAS
FROM tbDisciplina AS D JOIN tbOfertaDisciplina AS OD
ON D.DIS_CODIGO = OD.DIS_CODIGO
WHERE ODI_SEMESTRE = 2 AND ODI_ANO = 2014) AS QTDE_DISCIPLINAS, 
(SELECT COUNT (DISTINCT C.CUR_CODIGO) QTDE_CURSOS
FROM tbCurso AS C JOIN tbDisciplina AS D
ON C.CUR_CODIGO = D.CUR_CODIGO
JOIN 
tbOfertaDisciplina AS OD
ON D.DIS_CODIGO = OD.DIS_CODIGO
WHERE ODI_SEMESTRE = 2 AND ODI_ANO = 2014) AS QTDE_CURSOS , 
(SELECT COUNT (DISTINCT P.PRO_CODIGO) QTDE_PROFESSORES
FROM tbProfessor AS P JOIN tbOfertaDisciplina AS OD
ON P.PRO_CODIGO = OD.PRO_CODIGO
WHERE ODI_SEMESTRE = 2 AND ODI_ANO = 2014) AS QTDE_PROFESSORES,
(SELECT COUNT (*) QTDE_ALUNOS
FROM tbAluno AS A JOIN tbAlunoMatricula AS AM
ON A.ALU_CODIGO = AM.ALU_CODIGO
JOIN 
tbOfertaDisciplina AS OD
ON AM.ODI_CODIGO = OD.DIS_CODIGO
WHERE ODI_SEMESTRE = 2 AND ODI_ANO = 2014) AS QTDE_ALUNOS  

