use SistemaAcademicoBCC

→ Obter o nome do curso que possui a maior quantidade de
disciplinas.

SELECT CUR_NOME, COUNT(*) AS QTDE_DISCIPLINAS
FROM tbCurso AS C JOIN tbDisciplina AS D
ON C.CUR_CODIGO = D.CUR_CODIGO
GROUP BY CUR_NOME
HAVING COUNT (*) = (SELECT MAX(QTDE_DISCIPLINAS)
                   FROM
                   (SELECT COUNT(*) AS QTDE_DISCIPLINAS, C.CUR_CODIGO
                    FROM tbCurso AS C JOIN tbDisciplina AS D
                    ON C.CUR_CODIGO = D.CUR_CODIGO
                    GROUP BY C.CUR_CODIGO)T)

SELECT CUR_NOME
FROM VWCursoDisciplina
WHERE QTDE_DISCIPLINAS = (SELECT MAX(QTDE_DISCIPLINAS)
                   FROM VWCursoDisciplina)

                 

POR MEIO DE UMA VISÃO

CREATE VIEW VWDISCIPLINASCURSO
AS
SELECT COUNT(*) AS QTDE_DISCIPLINAS, C.CUR_CODIGO, CUR_NOME
                    FROM tbCurso AS C JOIN tbDisciplina AS D
                    ON C.CUR_CODIGO = D.CUR_CODIGO
                    GROUP BY C.CUR_CODIGO, CUR_NOME
SELECT * FROM VWDISCIPLINASCURSO

→ Obter o nome do curso de graduação que possui a maior
quantidade de alunos.

SELECT CUR_NOME, COUNT(*) AS QTDE_ALUNOS
FROM tbAluno AS A JOIN tbCurso AS C
ON A.CUR_CODIGO = C.CUR_CODIGO
WHERE CUR_NIVEL = 'GRADUAÇÃO'
GROUP BY CUR_NOME
HAVING COUNT (*)  = (SELECT MAX(QTDE_ALUNOS)
FROM
(SELECT COUNT (*) AS QTDE_ALUNOS , C.CUR_CODIGO
 FROM tbAluno AS A JOIN tbCurso AS C
ON A.CUR_CODIGO = C.CUR_CODIGO
GROUP BY C.CUR_CARGA_HORARIA, C.CUR_CODIGO)T)

POR MEIO DE UMA VISÃO

ALTER VIEW VWALUNOSCURSO
AS
SELECT COUNT (*) AS QTDE_ALUNOS , C.CUR_CODIGO, CUR_NOME
 FROM tbAluno AS A JOIN tbCurso AS C
ON A.CUR_CODIGO = C.CUR_CODIGO
WHERE CUR_NIVEL = 'GRADUAÇÃO'
GROUP BY C.CUR_CODIGO, CUR_NOME

SELECT CUR_NOME
FROM VWALUNOSCURSO
WHERE  QTDE_ALUNOS = (SELECT MAX(QTDE_ALUNOS) FROM VWALUNOSCURSO)







