use SistemaAcademicoBCC

a) Obter o nome do curso que possui a maior quantidade de disciplinas ofertada no
semestre 2018.1.

CREATE VIEW VWMAIORQTDE
AS 
SELECT CUR_NOME, COUNT (*) QTDE_DISCIPLINAS
FROM tbCurso AS C JOIN tbDisciplina AS D
ON C.CUR_CODIGO = D.CUR_CODIGO
JOIN
tbOfertaDisciplina AS OD
ON D.DIS_CODIGO = OD.DIS_CODIGO
WHERE ODI_SEMESTRE = 2 AND ODI_ANO = 2014
GROUP BY CUR_NOME

SELECT * FROM VWMAIORQTDE

SELECT CUR_NOME
FROM VWMAIORQTDE
WHERE QTDE_DISCIPLINAS = (SELECT MAX(QTDE_DISCIPLINAS) FROM VWMAIORQTDE)

b) Crie uma view para obter o nome do aluno, as disciplinas cursadas e a quantidade de
vezes que cursou cada disciplina.

CREATE VIEW VWALUNODISCIPLINA
AS 
SELECT ALU_NOME, DIS_NOME , COUNT (*) AS QTDE
FROM tbAluno AS A JOIN tbAlunoMatricula AS AM
ON A.ALU_CODIGO = AM.ALU_CODIGO
JOIN
tbOfertaDisciplina AS OD
ON AM.ODI_CODIGO = OD.ODI_CODIGO
JOIN
tbDisciplina AS D
ON OD.DIS_CODIGO = D.DIS_CODIGO
GROUP BY ALU_NOME, DIS_NOME

c) Obter o nome do aluno que mais cursou a disciplina de Introdução a Programação.

CREATE VIEW VWALUNOCURSO
AS
SELECT COUNT(*) AS QTDE , ALU_NOME
FROM tbAluno AS A JOIN tbAlunoMatricula AS AM
ON A.ALU_CODIGO = AM.ALU_CODIGO
JOIN
tbOfertaDisciplina AS OD
ON AM.ODI_CODIGO = OD.ODI_CODIGO
JOIN
tbDisciplina AS D
ON OD.DIS_CODIGO = D.DIS_CODIGO
WHERE DIS_NOME = 'INTRODUÇÃO A PROGRAMAÇÃO'
GROUP BY ALU_NOME

SELECT * FROM VWALUNOCURSO

SELECT ALU_NOME 
FROM VWALUNOCURSO
WHERE QTDE = (SELECT MAX(QTDE) FROM VWALUNOCURSO)

d) Obter o nome do aluno do curso de Ciência da Computação que cursa menos créditos
no semestre 2018.1.

ALTER VIEW VWALUNOMENOR
AS
SELECT ALU_NOME , SUM (DIS_CARGA_HORARIA) QTDE
FROM tbAluno AS A JOIN tbAlunoMatricula AS AM
ON A.ALU_CODIGO = AM.ALU_CODIGO
JOIN
tbOfertaDisciplina AS OD
ON AM.ODI_CODIGO = OD.ODI_CODIGO
JOIN
tbDisciplina AS D
ON OD.DIS_CODIGO = D.DIS_CODIGO
JOIN
tbCurso AS C
ON D.CUR_CODIGO = D.DIS_CODIGO
WHERE CUR_NOME = 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO'
AND ODI_SEMESTRE = 2 AND ODI_ANO = 2014
GROUP BY ALU_NOME

SELECT * FROM VWALUNOMENOR

SELECT ALU_NOME
FROM VWALUNOMENOR
WHERE QTDE =  (SELECT MIN(QTDE) FROM VWALUNOCURSO)

e) Obter o nome do aluno do curso de Ciência da Computação que cursou o maior
número de disciplinas de outro curso.

CREATE VIEW VWALUNOMAIORDISCIPLINAS
AS
SELECT ALU_NOME , CUR_NOME, COUNT (*) QTDE
FROM tbAluno AS A JOIN tbAlunoMatricula AS AM
ON A.ALU_CODIGO = AM.ALU_CODIGO
JOIN
tbOfertaDisciplina AS OD
ON AM.ODI_CODIGO = OD.ODI_CODIGO
JOIN
tbDisciplina AS D
ON OD.DIS_CODIGO = D.DIS_CODIGO
JOIN
tbCurso AS C
ON D.CUR_CODIGO = D.DIS_CODIGO
GROUP BY ALU_NOME, CUR_NOME

SELECT * FROM VWALUNOCURSO

SELECT ALU_NOME
FROM VWALUNOMAIORDISCIPLINAS
WHERE CUR_NOME = 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO' AND 
QTDE = (SELECT MAX(QTDE) FROM VWALUNOCURSO WHERE CUR_NOME != 'BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO')