use SistemaAcademicoBCC

Obter o nome do professor que possui a maior carga horária
de disciplinas no semestre 2 do ano 2021.

ALTER VIEW VWPROFESSORCARGA
AS 
SELECT SUM(DIS_CARGA_HORARIA) AS MAIOR, PRO_NOME
FROM tbProfessor AS P JOIN tbOfertaDisciplina AS OD
ON P.PRO_CODIGO = OD.PRO_CODIGO
JOIN 
tbDisciplina AS D
ON OD.DIS_CODIGO = D.DIS_CODIGO
WHERE ODI_SEMESTRE = 2 AND ODI_ANO = 2014
GROUP BY PRO_NOME

SELECT * FROM VWPROFESSORCARGA

SELECT PRO_NOME
FROM VWPROFESSORCARGA
WHERE MAIOR = (SELECT MAX(MAIOR) FROM VWPROFESSORCARGA)



→ Obter o nome do professor que mais ministrou a disciplina de
Introdução a Programação.

CREATE VIEW VWPROFESSORDISCIPLINA
AS 
SELECT PRO_NOME, COUNT (*) MAIOR
FROM  tbProfessor AS P JOIN tbOfertaDisciplina AS OD
ON P.PRO_CODIGO = OD.PRO_CODIGO
JOIN 
tbDisciplina AS D
ON OD.DIS_CODIGO = D.DIS_CODIGO
WHERE DIS_NOME = 'Introdução a Programação'
GROUP BY PRO_NOME

SELECT * FROM VWPROFESSORDISCIPLINA

SELECT PRO_NOME
FROM VWPROFESSORDISCIPLINA
WHERE MAIOR = (SELECT MAX(MAIOR) FROM VWPROFESSORDISCIPLINA)

SELECT PRO_NOME, COUNT(*) QTDE
FROM  tbProfessor AS P JOIN tbOfertaDisciplina AS OD
ON P.PRO_CODIGO = OD.PRO_CODIGO
JOIN 
tbDisciplina AS D
ON OD.DIS_CODIGO = D.DIS_CODIGO
WHERE DIS_NOME = 'Introdução a Programação'
GROUP BY PRO_NOME
HAVING COUNT (*) = (SELECT MAX(QTDE) 
FROM (SELECT COUNT(*) QTDE
FROM  tbProfessor AS P JOIN tbOfertaDisciplina AS OD
ON P.PRO_CODIGO = OD.PRO_CODIGO
JOIN 
tbDisciplina AS D
ON OD.DIS_CODIGO = D.DIS_CODIGO
WHERE DIS_NOME = 'Introdução a Programação') T)